
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springdb
    username: root
    password: root123
  thymeleaf:
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    check-template-location: true

mybatis:
  mapper-locations: classpath:/mappers/**/*Mapper.xml
